# 直接使用 Nginx 生产环境镜像
FROM nginx:alpine

# 将 GitHub Actions 刚才在宿主机打包好的 dist 目录直接复制进来
# 注意：不需要 --from=build 了，直接从 Actions 的工作目录读取
COPY osr-web/dist /usr/share/nginx/html

# 复制 nginx 配置文件
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
