/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedNumber: typeof import('./components/AnimatedNumber.vue')['default']
    AppUpdatePrompt: typeof import('./components/AppUpdatePrompt.vue')['default']
    ChangePasswordDialog: typeof import('./components/ChangePasswordDialog.vue')['default']
    CopyTaskFormDialog: typeof import('./components/dialogs/CopyTaskFormDialog.vue')['default']
    DirectoryTreeSelect: typeof import('./components/DirectoryTreeSelect/index.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    FormDialogShell: typeof import('./components/dialogs/FormDialogShell.vue')['default']
    FormField: typeof import('./components/FormField.vue')['default']
    FullTextDialog: typeof import('./components/mobile/FullTextDialog.vue')['default']
    GlobalFeedback: typeof import('./components/GlobalFeedback.vue')['default']
    MiniTrend: typeof import('./components/MiniTrend.vue')['default']
    MobileActionSheet: typeof import('./components/mobile/MobileActionSheet.vue')['default']
    MobileBatchBar: typeof import('./components/mobile/MobileBatchBar.vue')['default']
    MobileListPage: typeof import('./components/mobile/MobileListPage.vue')['default']
    MobileMorePanel: typeof import('./components/mobile/MobileMorePanel.vue')['default']
    MobilePager: typeof import('./components/mobile/MobilePager.vue')['default']
    MobileSearchPanel: typeof import('./components/mobile/MobileSearchPanel.vue')['default']
    MobileTabBar: typeof import('./components/mobile/MobileTabBar.vue')['default']
    MobileTabSettingsDialog: typeof import('./components/mobile/MobileTabSettingsDialog.vue')['default']
    OpenListTree: typeof import('./components/OpenListTree.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PtAutoAddRuleFormDialog: typeof import('./components/dialogs/PtAutoAddRuleFormDialog.vue')['default']
    PtCleanRuleDialog: typeof import('./components/dialogs/PtCleanRuleDialog.vue')['default']
    PtDownloaderFormDialog: typeof import('./components/dialogs/PtDownloaderFormDialog.vue')['default']
    PtIndexerFormDialog: typeof import('./components/dialogs/PtIndexerFormDialog.vue')['default']
    PtMediaServerFormDialog: typeof import('./components/dialogs/PtMediaServerFormDialog.vue')['default']
    PtTorrentBlacklistFormDialog: typeof import('./components/dialogs/PtTorrentBlacklistFormDialog.vue')['default']
    PtTransferRuleFormDialog: typeof import('./components/dialogs/PtTransferRuleFormDialog.vue')['default']
    RenameTaskFormDialog: typeof import('./components/dialogs/RenameTaskFormDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/SearchPanel.vue')['default']
    SidebarMenuItem: typeof import('./components/SidebarMenuItem.vue')['default']
    StatusChip: typeof import('./components/StatusChip.vue')['default']
    StrmTaskFormDialog: typeof import('./components/dialogs/StrmTaskFormDialog.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
    TreeNodeItem: typeof import('./components/TreeNodeItem.vue')['default']
    WecomUserFormDialog: typeof import('./components/dialogs/WecomUserFormDialog.vue')['default']
  }
}
